# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApplePaySDKExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'CommonDataModelsKit-iOS'
  # Pods for ApplePaySDKExample

end

target 'tapapplepaysdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tapapplepaysdk
 pod 'CommonDataModelsKit-iOS'
 pod 'TapNetworkKit-iOS'
 pod 'TapApplicationV2'
end
